/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package consuming;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Soartest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4621938607040404881L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Soartest\",\"namespace\":\"consuming\",\"fields\":[{\"name\":\"rec\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Soartest> ENCODER =
      new BinaryMessageEncoder<Soartest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Soartest> DECODER =
      new BinaryMessageDecoder<Soartest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Soartest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Soartest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Soartest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Soartest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Soartest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Soartest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Soartest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Soartest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence rec;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Soartest() {}

  /**
   * All-args constructor.
   * @param rec The new value for rec
   */
  public Soartest(java.lang.CharSequence rec) {
    this.rec = rec;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rec;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rec = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'rec' field.
   * @return The value of the 'rec' field.
   */
  public java.lang.CharSequence getRec() {
    return rec;
  }


  /**
   * Sets the value of the 'rec' field.
   * @param value the value to set.
   */
  public void setRec(java.lang.CharSequence value) {
    this.rec = value;
  }

  /**
   * Creates a new Soartest RecordBuilder.
   * @return A new Soartest RecordBuilder
   */
  public static consuming.Soartest.Builder newBuilder() {
    return new consuming.Soartest.Builder();
  }

  /**
   * Creates a new Soartest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Soartest RecordBuilder
   */
  public static consuming.Soartest.Builder newBuilder(consuming.Soartest.Builder other) {
    if (other == null) {
      return new consuming.Soartest.Builder();
    } else {
      return new consuming.Soartest.Builder(other);
    }
  }

  /**
   * Creates a new Soartest RecordBuilder by copying an existing Soartest instance.
   * @param other The existing instance to copy.
   * @return A new Soartest RecordBuilder
   */
  public static consuming.Soartest.Builder newBuilder(consuming.Soartest other) {
    if (other == null) {
      return new consuming.Soartest.Builder();
    } else {
      return new consuming.Soartest.Builder(other);
    }
  }

  /**
   * RecordBuilder for Soartest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Soartest>
    implements org.apache.avro.data.RecordBuilder<Soartest> {

    private java.lang.CharSequence rec;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(consuming.Soartest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rec)) {
        this.rec = data().deepCopy(fields()[0].schema(), other.rec);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Soartest instance
     * @param other The existing instance to copy.
     */
    private Builder(consuming.Soartest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.rec)) {
        this.rec = data().deepCopy(fields()[0].schema(), other.rec);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'rec' field.
      * @return The value.
      */
    public java.lang.CharSequence getRec() {
      return rec;
    }


    /**
      * Sets the value of the 'rec' field.
      * @param value The value of 'rec'.
      * @return This builder.
      */
    public consuming.Soartest.Builder setRec(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rec = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rec' field has been set.
      * @return True if the 'rec' field has been set, false otherwise.
      */
    public boolean hasRec() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rec' field.
      * @return This builder.
      */
    public consuming.Soartest.Builder clearRec() {
      rec = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Soartest build() {
      try {
        Soartest record = new Soartest();
        record.rec = fieldSetFlags()[0] ? this.rec : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Soartest>
    WRITER$ = (org.apache.avro.io.DatumWriter<Soartest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Soartest>
    READER$ = (org.apache.avro.io.DatumReader<Soartest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.rec);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rec = in.readString(this.rec instanceof Utf8 ? (Utf8)this.rec : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rec = in.readString(this.rec instanceof Utf8 ? (Utf8)this.rec : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










